### ISSUE TITLE
Issues about multiweather U1652 transforms

### ISSUE THREAD

**Issue by Frost24K** [SummerpanKing/DAC#1]
Hi,

Thank you for providing this excellent work! I encountered some issues when trying to use the transform list to generate multi-weather U1652 data:

**ValueError:** "Blur limit must be 0 or odd. Got: (10, 12)" in line 81 of sample4geo/transforms.py.
**AttributeError:** "module 'albumentations' has no attribute 'BlendAlphaOverlay'" in line 82 of sample4geo/transforms.py.
Could you please assist me in resolving these issues? I would greatly appreciate your help!

Thank you in advance!

**Comment by SummerpanKing** [comment]
Thank you for your interest! It appears the issue might be related to the versions of python packages. Below, you'll find the detailed version information for my conda environment. I hope this helps resolve the issue. If you encounter any further problems, please don't hesitate to reach out. 

# packages in environment at /home/xiapanwang/.conda/envs/CVGL:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.1.0                    pypi_0    pypi
albumentations            1.4.0                    pypi_0    pypi
anyio                     4.2.0            py39h06a4308_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h7f8727e_0  
asttokens                 2.4.1                    pypi_0    pypi
async-lru                 2.0.4            py39h06a4308_0  
attrs                     23.1.0           py39h06a4308_0  
babel                     2.11.0           py39h06a4308_0  
backcall                  0.2.0              pyhd3eb1b0_0  
bcrypt                    4.1.2                    pypi_0    pypi
beautifulsoup4            4.12.2           py39h06a4308_0  
bleach                    4.1.0              pyhd3eb1b0_0  
brotli-python             1.0.9            py39h6a678d5_7  
bzip2                     1.0.8                h5eee18b_5  
ca-certificates           2024.3.11            h06a4308_0  
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.16.0           py39h5eee18b_0  
charset-normalizer        2.1.1                    pypi_0    pypi
comm                      0.2.1            py39h06a4308_0  
contourpy                 1.2.0                    pypi_0    pypi
cryptography              42.0.5                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cyrus-sasl                2.1.28               h52b45da_1  
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.6.7            py39h6a678d5_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
einops                    0.7.0                    pypi_0    pypi
exceptiongroup            1.2.0            py39h06a4308_0  
executing                 2.0.1                    pypi_0    pypi
expat                     2.5.0                h6a678d5_0  
filelock                  3.9.0                    pypi_0    pypi
fontconfig                2.14.1               h4c34cd2_2  
fonttools                 4.49.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
fsspec                    2024.2.0                 pypi_0    pypi
geographiclib             2.0                      pypi_0    pypi
geopy                     2.4.1                    pypi_0    pypi
glib                      2.78.4               h6a678d5_0  
glib-tools                2.78.4               h6a678d5_0  
grpcio                    1.62.0                   pypi_0    pypi
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
huggingface-hub           0.20.3                   pypi_0    pypi
icu                       73.1                 h6a678d5_0  
idna                      3.4              py39h06a4308_0  
imageio                   2.34.0                   pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        7.0.1            py39h06a4308_0  
importlib-resources       6.1.1                    pypi_0    pypi
importlib_metadata        7.0.1                hd3eb1b0_0  
ipykernel                 6.28.0           py39h06a4308_0  
ipython                   8.18.1                   pypi_0    pypi
ipywidgets                8.1.2            py39h06a4308_0  
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.19.2           py39h06a4308_0  
jsonschema-specifications 2023.7.1         py39h06a4308_0  
jupyter                   1.0.0            py39h06a4308_9  
jupyter-lsp               2.2.0            py39h06a4308_0  
jupyter_client            8.6.0            py39h06a4308_0  
jupyter_console           6.6.3            py39h06a4308_0  
jupyter_core              5.5.0            py39h06a4308_0  
jupyter_events            0.8.0            py39h06a4308_0  
jupyter_server            2.10.0           py39h06a4308_0  
jupyter_server_terminals  0.4.4            py39h06a4308_1  
jupyterlab                4.0.11           py39h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.25.1           py39h06a4308_0  
jupyterlab_widgets        3.0.10           py39h06a4308_0  
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.20.1               h143b758_1  
lazy-loader               0.3                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libclang                  14.0.6          default_hc6dbbc7_1  
libclang13                14.0.6          default_he11475f_1  
libcups                   2.4.2                h2d74bed_1  
libedit                   3.1.20230828         h5eee18b_0  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libglib                   2.78.4               hdc74915_0  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libllvm14                 14.0.6               hdb19cb5_3  
libpng                    1.6.39               h5eee18b_0  
libpq                     12.17                hdbd6064_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
libxcb                    1.15                 h7f8727e_0  
libxkbcommon              1.0.1                h5eee18b_1  
libxml2                   2.10.4               hf1b16e4_1  
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.5.2                    pypi_0    pypi
markupsafe                2.1.3            py39h5eee18b_0  
matplotlib                3.8.3                    pypi_0    pypi
matplotlib-inline         0.1.6            py39h06a4308_0  
mistune                   2.0.4            py39h06a4308_0  
mpmath                    1.3.0                    pypi_0    pypi
mysql                     5.7.24               h721c034_2  
nbclient                  0.8.0            py39h06a4308_0  
nbconvert                 7.10.0           py39h06a4308_0  
nbformat                  5.9.2            py39h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.6.0            py39h06a4308_0  
networkx                  3.2.1                    pypi_0    pypi
notebook                  7.0.8            py39h06a4308_0  
notebook-shim             0.2.3            py39h06a4308_0  
numpy                     1.26.4                   pypi_0    pypi
nvidia-cublas-cu11        11.11.3.6                pypi_0    pypi
nvidia-cuda-cupti-cu11    11.8.87                  pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.8.89                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.8.89                  pypi_0    pypi
nvidia-cudnn-cu11         8.7.0.84                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.3.0.86                pypi_0    pypi
nvidia-cusolver-cu11      11.4.1.48                pypi_0    pypi
nvidia-cusparse-cu11      11.7.5.86                pypi_0    pypi
nvidia-nccl-cu11          2.19.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.8.86                  pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
opencv-python-headless    4.9.0.80                 pypi_0    pypi
openssl                   3.0.13               h7f8727e_0  
overrides                 7.4.0            py39h06a4308_0  
packaging                 23.2             py39h06a4308_0  
pandas                    2.2.1                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0  
paramiko                  3.4.0                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0  
pcre2                     10.42                hebb0a14_0  
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    10.2.0                   pypi_0    pypi
pip                       23.3.1           py39h06a4308_0  
platformdirs              3.10.0           py39h06a4308_0  
ply                       3.11             py39h06a4308_0  
prometheus_client         0.14.1           py39h06a4308_0  
prompt-toolkit            3.0.43           py39h06a4308_0  
prompt_toolkit            3.0.43               hd3eb1b0_0  
protobuf                  4.25.3                   pypi_0    pypi
psutil                    5.9.0            py39h5eee18b_0  
ptflops                   0.7.2.2                  pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.17.2                   pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pyqt                      5.15.10          py39h6a678d5_0  
pyqt5-sip                 12.13.0          py39h5eee18b_0  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.18               h955ad1f_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py39h06a4308_0  
python-json-logger        2.0.7            py39h06a4308_0  
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1            py39h5eee18b_0  
pyzmq                     25.1.2           py39h6a678d5_0  
qt-main                   5.15.2              h53bd1ea_10  
qtconsole                 5.5.1            py39h06a4308_0  
qtpy                      2.4.1            py39h06a4308_0  
qudida                    0.0.4                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.30.2           py39h06a4308_0  
regex                     2023.12.25               pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
rfc3339-validator         0.1.4            py39h06a4308_0  
rfc3986-validator         0.1.1            py39h06a4308_0  
rpds-py                   0.10.6           py39hb02cf49_0  
safetensors               0.4.2                    pypi_0    pypi
scikit-image              0.22.0                   pypi_0    pypi
scikit-learn              1.4.1.post1              pypi_0    pypi
scipy                     1.12.0                   pypi_0    pypi
send2trash                1.8.2            py39h06a4308_0  
setuptools                68.2.2           py39h06a4308_0  
shapely                   2.0.4                    pypi_0    pypi
sip                       6.7.12           py39h6a678d5_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.3.0            py39h06a4308_0  
soupsieve                 2.5              py39h06a4308_0  
sqlite                    3.41.2               h5eee18b_0  
stack-data                0.6.3                    pypi_0    pypi
stack_data                0.2.0              pyhd3eb1b0_0  
sympy                     1.12                     pypi_0    pypi
tensorboard               2.16.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
terminado                 0.17.1           py39h06a4308_0  
threadpoolctl             3.3.0                    pypi_0    pypi
tifffile                  2024.2.12                pypi_0    pypi
timm                      0.9.16                   pypi_0    pypi
tinycss2                  1.2.1            py39h06a4308_0  
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.15.2                   pypi_0    pypi
tomli                     2.0.1            py39h06a4308_0  
torch                     2.2.0+cu118              pypi_0    pypi
torchaudio                2.2.0+cu118              pypi_0    pypi
torchvision               0.17.0+cu118             pypi_0    pypi
tornado                   6.3.3            py39h5eee18b_0  
tqdm                      4.66.2                   pypi_0    pypi
traitlets                 5.14.1                   pypi_0    pypi
transformers              4.38.1                   pypi_0    pypi
triton                    2.2.0                    pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
typing_extensions         4.9.0            py39h06a4308_1  
tzdata                    2024.1                   pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webencodings              0.5.1            py39h06a4308_1  
websocket-client          0.58.0           py39h06a4308_4  
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2           py39h06a4308_0  
widgetsnbextension        4.0.10           py39h06a4308_0  
xz                        5.4.5                h5eee18b_0  
yaml                      0.2.5                h7b6447c_0  
zeromq                    4.3.5                h6a678d5_0  
zipp                      3.17.0           py39h06a4308_0  
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0

**Comment by Frost24K** [comment]
Hi,
Thank you for your quick response. I'll check packages' version and see if it works
