### ISSUE TITLE
University-1652 dataset testing

### ISSUE THREAD

**Issue by ziqianmo** [SummerpanKing/DAC#2]
Why does University-1652 perform well during validation but poorly during testing?

**Comment by SummerpanKing** [comment]
I have replied to your email; please check it.

**Comment by tianyi1565** [comment]
I have the same question, can you give me an answer? thank you.

**Comment by SummerpanKing** [comment]
> I have the same question, can you give me an answer? thank you.

Could you provide more details about the problem you encountered?

**Comment by tianyi1565** [comment]
Thank you for your reply. The current problem will be solved. Thank you.




| |
gefawei0822
|
|
***@***.***
|
---- Replied Message ----
| From | Panwang ***@***.***> |
| Date | 9/4/2025 10:43 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [SummerpanKing/DAC] University-1652 dataset testing (Issue #2) |
SummerpanKing left a comment (SummerpanKing/DAC#2)

I have the same question, can you give me an answer? thank you.

Could you provide more details about the problem you encountered?
